---
title: "Client Report - Can You Predict That?"
subtitle: "Course DS 250"
author: "[Ronaldo Monteiro]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
from sklearn.model_selection import train_test_split
from sklearn import metrics
import seaborn as sns

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from IPython.display import display
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here

# import your data here using pandas and the URL

df = pd.read_csv("https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv")
df
```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

## QUESTION|TASK 1

__Create 2-3 charts that evaluate potential relationships between the home variables and `before1980`.__ Explain what you learn from the charts that could help a machine learning algorithm. 

_type your results and analysis here_

```{python}
# Include and execute your code here
h_subset = df.filter(['livearea', 'stories', 'finbsmnt','basement', 'before1980']).sample(500)

# List of variables to be plotted in the pairplot
vars_to_plot = ['livearea', 'stories', 'before1980']
# This line uses the seaborn library to create a pairplot of the selected variables in h_subset.
# The 'hue' parameter is set to 'before1980', which means that the data points will be colored
# based on the values in the 'before1980' column.
sns.pairplot(h_subset[vars_to_plot], hue = 'before1980')
# This line calculates the correlation matrix for the columns in h_subset excluding the 'before1980' column.
# The correlation matrix is a table showing correlation coefficients between variables.
corr = h_subset.drop(columns = 'before1980').corr()

```


## QUESTION|TASK 2

__Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Explain your final model choice (algorithm, tuning parameters, etc) and describe what other models you tried.  

_type your results and analysis here_

```{python}
# Include and execute your code here
# Initialize the Random Forest classifier with a specified maximum depth
forest_DT = RandomForestClassifier(max_depth = 30)

# x = ml.filter(['livearea', 'stories', 'finbsmnt', 'numbaths', 'numbdrm', 'nocars', 'basement'])
# Feature selection: Exclude 'parcel', 'yrbuilt', and 'before1980' columns
x = df.drop(['parcel', 'yrbuilt', 'before1980'], axis = 1)
# Define the target variable
y = df.before1980
# Split the dataset into training and testing sets 
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.99, random_state = 5)
# Train the Random Forest classifier on the training set
forest_DT.fit(x_train, y_train)

# Make predictions on the test set 
y_predicted = forest_DT.predict(x_test)
# Evaluate and print the accuracy of the classifier
print('Accuracy: ',  metrics.accuracy_score(y_test, y_predicted))


```


## QUESTION|TASK 3

__Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a feature importance chart and a description of the features. 

_type your results and analysis here_

```{python}
# Include and execute your code here
# Accessing the feature importances from the trained Random Forest classifier
forest_DT.feature_importances_

# Creating a DataFrame to organize feature names and their corresponding importances
feature_df = pd.DataFrame({'features':x.columns, 'importance':forest_DT.feature_importances_}).sort_values('importance', ascending= True)
 
# Visualizing feature importances using Lets_plot

(
    ggplot(feature_df, aes(x='importance', y=as_discrete('features', order_by='importance'))) +
    geom_bar(stat='identity', fill='lightgreen') +
    labs(title='Important Features (high to low)', x='Importance', y='Features') +
    theme_minimal() +
    coord_flip() +
    ggsize(800, 1500)
)



```


## QUESTION|TASK 4

__Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to interpret each of the evaluation metrics you use.  

_type your results and analysis here_

```{python}
# Include and execute your code here
from lets_plot import *
LetsPlot.setup_html(no_js=True)

# Criar DataFrame
evaluation = pd.DataFrame({
    'Metrics': ['Accuracy', 'Recall', 'Precision'],
    'Values': [
        metrics.accuracy_score(y_test, y_predicted),
        metrics.recall_score(y_test, y_predicted),
        metrics.precision_score(y_test, y_predicted)
    ]
})

# Gráfico com Lets-Plot (estático compatível com Quarto)
(
    ggplot(evaluation, aes(x='Values', y='Metrics')) +
    geom_bar(stat='identity', fill='#87CEEB') +
    labs(title='Evaluation', x='Values', y='Metrics') +
    theme_minimal()
)


```

---

## STRETCH QUESTION|TASK 1

__Repeat the classification model using 3 different algorithms.__ Display their Feature Importance, and Decision Matrix. Explian the differences between the models and which one you would recommend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here



```


## STRETCH QUESTION|TASK 2

__Join the `dwellings_neighborhoods_ml.csv` data to the `dwelling_ml.csv` on the `parcel` column to create a new dataset. Duplicate the code for the stretch question above and update it to use this data.__ Explain the differences and if this changes the model you recomend to the Client.   

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 3

__Can you build a model that predicts the year a house was built?__ Explain the model and the evaluation metrics you would use to determine if the model is good.  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---
