---
title: "Client Report - The War with Star Wars"
subtitle: "Course DS 250"
author: "[RONALDO MONTEIRO]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)

```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here

# import your data here using pandas and the URL
df = pd.read_csv("https://github.com/fivethirtyeight/data/raw/master/star-wars-survey/StarWars.csv", encoding_errors="ignore")
df.head(3)

```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

## QUESTION|TASK 1

__Shorten the column names and clean them up for easier use with pandas.__ Provide a table or list that exemplifies how you fixed the names. 

_type your results and analysis here_

```{python}
# Renaming colunms (simplifying)

df.columns = [
    'respondent_id', 'seen_any_movie', 'fan', 'seen_ep1', 'seen_ep2', 'seen_ep3',
    'seen_ep4', 'seen_ep5', 'seen_ep6', 'rank_ep1', 'rank_ep2', 'rank_ep3', 
    'rank_ep4', 'rank_ep5', 'rank_ep6', 'han_solo', 'luke_skywalker', 'princess_leia',
    'anakin_skywalker', 'obi_wan', 'palpatine', 'darth_vader', 'lando_calrissian',
    'boba_fett', 'c3po', 'r2d2', 'jar_jar_binks', 'padme_amidala', 'yoda',
    'shot_first', 'know_exp_universe', 'fan_exp_universe',
    'fan_star_trek', 'gender', 'age', 'household_income', 'education', 'location'
]
df

# Creating a DataFrame comparing original and cleaned column names
column_comparison = pd.DataFrame({
    'Original Name': [
        'RespondentID',
        'Have you seen any of the 6 films in the Star Wars franchise?',
        'Do you consider yourself to be a fan of the Star Wars film franchise?',
        'Which of the following Star Wars films have you seen? (Ep.1)',
        'Unnamed: 4 (Ep.2)',
        'Unnamed: 5 (Ep.3)',
        'Unnamed: 6 (Ep.4)',
        'Unnamed: 7 (Ep.5)',
        'Unnamed: 8 (Ep.6)',
        'Please rank the Star Wars films in order of preference (Ep.1)',
        'Unnamed: 10 (Ep.2)',
        'Unnamed: 11 (Ep.3)',
        'Unnamed: 12 (Ep.4)',
        'Unnamed: 13 (Ep.5)',
        'Unnamed: 14 (Ep.6)',
        'Favorability of character (Han Solo)',
        'Unnamed: 16 (Luke Skywalker)',
        'Unnamed: 17 (Princess Leia)',
        'Unnamed: 18 (Anakin Skywalker)',
        'Unnamed: 19 (Obi-Wan Kenobi)',
        'Unnamed: 20 (Palpatine)',
        'Unnamed: 21 (Darth Vader)',
        'Unnamed: 22 (Lando Calrissian)',
        'Unnamed: 23 (Boba Fett)',
        'Unnamed: 24 (C-3PO)',
        'Unnamed: 25 (R2-D2)',
        'Unnamed: 26 (Jar Jar Binks)',
        'Unnamed: 27 (Padme Amidala)',
        'Unnamed: 28 (Yoda)',
        'Which character shot first?',
        'Are you familiar with the Expanded Universe?',
        'Do you consider yourself to be a fan of the Expanded Universe?',
        'Do you consider yourself to be a fan of the Star Trek franchise?',
        'Gender',
        'Age',
        'Household Income',
        'Education',
        'Location (Census Region)'
    ],
    'Cleaned Name': [
        'respondent_id', 'seen_any_movie', 'fan', 'seen_ep1', 'seen_ep2', 'seen_ep3',
        'seen_ep4', 'seen_ep5', 'seen_ep6', 'rank_ep1', 'rank_ep2', 'rank_ep3', 
        'rank_ep4', 'rank_ep5', 'rank_ep6', 'han_solo', 'luke_skywalker', 'princess_leia',
        'anakin_skywalker', 'obi_wan', 'palpatine', 'darth_vader', 'lando_calrissian',
        'boba_fett', 'c3po', 'r2d2', 'jar_jar_binks', 'padme_amidala', 'yoda',
        'shot_first', 'know_exp_universe', 'fan_exp_universe',
        'fan_star_trek', 'gender', 'age', 'household_income', 'education', 'location'
    ]
})

# Display the resulting table
column_comparison

```


## QUESTION|TASK 2

__Clean and format the data so that it can be used in a machine learning model.__ As you format the data, you should complete each item listed below. In your final report provide example(s) of the reformatted data with a short description of the changes made.  
    A. Filter the dataset to respondents that have seen at least one film  
    B. Create a new column that converts the age ranges to a single number. Drop the age range categorical column  
    C. Create a new column that converts the education groupings to a single number. Drop the school categorical column  
    D. Create a new column that converts the income ranges to a single number. Drop the income range categorical column  
    E. Create your target (also known as “y” or “label”) column based on the new income range column  
    F. One-hot encode all remaining categorical columns   

_type your results and analysis here_

```{python}
# Question A
# Columns that indicate whether a respondent has seen a specific Star Wars movie
seen_movie_columns = ['seen_ep1', 'seen_ep2', 'seen_ep3', 'seen_ep4', 'seen_ep5', 'seen_ep6']

# Filtering dataset to keep only respondents who have seen at least one movie
df_filtered = df[df[seen_movie_columns].notnull().any(axis=1)]

# Displaying the first few rows to verify the result
df_filtered.head()

```

```{python}
# Question B
import numpy as np

# Remove invalid rows containing the string 'Response' in age column
df_filtered = df_filtered[df_filtered['age'] != 'Response']

# Mapping dictionary to convert age ranges into numerical midpoints
age_mapping = {
    '18-29': 24,
    '30-44': 37,
    '45-60': 52,
    '> 60': 65,
    np.nan: None
}

# Creating a numeric age column
df_filtered['age_numeric'] = df_filtered['age'].map(age_mapping)

# Dropping the original categorical column
df_filtered.drop('age', axis=1, inplace=True)

# Checking the result
df_filtered[['respondent_id', 'age_numeric']].head()

```

```{python}
# Question C

# Check unique values in the original education column
print(df_filtered['education'].unique())

# Define a mapping dictionary to convert education categories to numerical values
education_mapping = {
    'Less than high school degree': 1,
    'High school degree': 2,
    'Some college or Associate degree': 3,
    'Bachelor degree': 4,
    'Graduate degree': 5,
    np.nan: None
}

# Create a new numerical column 'education_numeric'
df_filtered['education_numeric'] = df_filtered['education'].map(education_mapping)

# Drop the original categorical education column
df_filtered.drop('education', axis=1, inplace=True)

# Displaying first rows to check the results
df_filtered[['respondent_id', 'education_numeric']].head(10)


```

```{python}
# Question D

# Mapping dictionary for income categories to numerical midpoints
income_mapping = {
    '$0 - $24,999': 12500,
    '$25,000 - $49,999': 37500,
    '$50,000 - $99,999': 75000,
    '$100,000 - $149,999': 125000,
    '$150,000+': 150000,
    np.nan: None
}

# Create a numerical income column
df_filtered['income_numeric'] = df_filtered['household_income'].map(income_mapping)

# Drop the original categorical income column
df_filtered.drop('household_income', axis=1, inplace=True)

# Check the result
df_filtered[['respondent_id', 'income_numeric']].head(10)



```

```{python}
# Include and execute your code here


```

```{python}
# Include and execute your code here


```

## QUESTION|TASK 3

__Validate that the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article.__  

_type your results and analysis here_

```{python}
# Include and execute your code here

```

```{python}
# Include and execute your code here

```

## QUESTION|TASK 4

__Build a machine learning model that predicts whether a person makes more than $50k. Describe your model and report the accuracy.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here

```

---

## STRETCH QUESTION|TASK 1

__Build a machine learning model that predicts whether a person makes more than $50k. With accuracy of at least 65%. Describe your model and report the accuracy.__

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 2

__Validate the data provided on GitHub lines up with the article by recreating a 3rd visual from the article.__

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 3

__Create a new column that converts the location groupings to a single number. Drop the location categorical column.__  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---
